### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by MisterGamer0001** [metonator/GameLauncher_NFSW#1]
Hello! :) I registered with a password of 17 characters. But when I want to log in, it only lets me enter 16 characters of password. I have tried resetting the password but it will not let me. It shows me "ERROR: Can not send email!".
How can it be fixed? I really want to play Need For Speed Wolrd again ... it's a gem :"). Thank you!!!!!!! Greetings from Argentina!!!!!!!
![error](https://user-images.githubusercontent.com/30632287/28837619-d4c7ae14-76c3-11e7-85ed-dbffd625d506.png)

**Comment by metonator** [comment]
I've fixed that issue [here](https://github.com/metonator/GameLauncher_NFSW/releases/tag/AppveyorBuild-1.0.42), now you should be able to login.

**Comment by MisterGamer0001** [comment]
![sin titulo](https://user-images.githubusercontent.com/30632287/28997220-904c743e-79e5-11e7-9298-3acd55cebdbd.png)

**Comment by metonator** [comment]
Oh, forgot i had issue with build machine, try this one: https://github.com/metonator/GameLauncher_NFSW/releases/tag/AppveyorBuild-1.0.124

**Comment by metonator** [comment]
Oh, forgot i had issue with build machine, try this one: https://github.com/metonator/GameLauncher_NFSW/releases/tag/AppveyorBuild-1.0.124

**Comment by metonator** [comment]
Oh, forgot i had issue with build machine, try this one: https://github.com/metonator/GameLauncher_NFSW/releases/tag/AppveyorBuild-1.0.124

**Comment by metonator** [comment]
Assuming issue was solved
