### ISSUE TITLE
"DownloadManager returned a null buffer, aborting"

### ISSUE THREAD

**Issue by Artyom15** [metonator/GameLauncher_NFSW#12]
I have a problem downloading the game data, when it reaches 2 Mb the download stops and I get this
"DownloadManager returned a null buffer, aborting"
Could you help me please?

**Comment by metonator** [comment]
Probably your antivirus is blocking access from gamelauncher to mirrorserver (nfsw.mtntr.eu). Make sure you have antivirus and firewall disabled.

**Comment by Artyom15** [comment]
I'll try

**Comment by Artyom15** [comment]
Thank you has been fixed, but now I have the infinite load screen

**Comment by metonator** [comment]
Guessing your name is "ARTYOM15", right?

**Comment by Artyom15** [comment]
My nick is Artyom

**Comment by Artyom15** [comment]
Server: SBRW Open Beta. Email: joaquin:ibanezxd@yahoo.com Nick: Artyom

**Comment by Artyom15** [comment]
Server: SBRW Open Beta. Email: joaquin_ibanezxd@yahoo.com Nick: Artyom

**Comment by metonator** [comment]
Okay, sent to admins to check what happens (also masked your email tl prevent spam)

**Comment by Artyom15** [comment]
thank you very much

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
