### ISSUE TITLE
Infinite loading 

### ISSUE THREAD

**Issue by MaNameZeref** [metonator/GameLauncher_NFSW#13]
Hello yesterday when i installed the game and launched it was working for like 10 min. then it crashed 
i reinstalled it everything and i have still that problem when i launch the game and the infinite loading screen pleas help ! i really want play nfsw agan :(
![image](https://user-images.githubusercontent.com/32129049/30640626-eb7a9a06-9e03-11e7-86e1-8af8e28c878f.png)

**Comment by metonator** [comment]
Ingame nickname?

**Comment by Artyom15** [comment]
I also have that problem

**Comment by MaNameZeref** [comment]
fixed just create a new acc

2017-09-20 23:00 GMT+02:00 Artyom15 <notifications@github.com>:

**Comment by VladImpaler** [comment]
Hi, I have the same problem, can you help me solve it? 
Thx in advance
Nickname in game: pr0digy

**Comment by MaNameZeref** [comment]
Welp i have it agan 
Name Z3REF Server SBRW Open Beta :(!

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
