### ISSUE TITLE
I Have Infinite Loading...........

### ISSUE THREAD

**Issue by Lisiasty** [metonator/GameLauncher_NFSW#14]
infinite loading...............

**Comment by jajo666** [comment]
i have this too...........................

**Comment by metonator** [comment]
Nicknames?

**Comment by Lisiasty** [comment]
Lisiasty my nickname. Email = th3hitplblondyn@gmail.com

**Comment by Lisiasty** [comment]
Lisiasty my nickname. server = SBRW Open Beta Email =
th3hitplblondyn@gmail.com

2017-09-20 20:28 GMT+02:00 Milan Suwała <notifications@github.com>:

**Comment by metonator** [comment]
Okay, lisiasty submitted to server admins (also, cleared your email to avoid spam)

**Comment by jajo666** [comment]
my nickname is JAJO server SBRW Open Beta e mail systemporsche12@wp.pl

**Comment by jajo666** [comment]
JAJO

**Comment by jajo666** [comment]
Thank You :)

**Comment by metonator** [comment]
Both submitted, should be fixed in short time
