### ISSUE TITLE
I Have Infinite Loading.

### ISSUE THREAD

**Issue by Wojziasty** [metonator/GameLauncher_NFSW#17]
My nick in game: Wojziu
Server: SBRW Open Beta

**Comment by metonator** [comment]
Submitted to serveradmin

**Comment by Kostek1327** [comment]
mój nick KOSTEK1327 Serwer SBRW Open Beta prosze o pomoc

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
