### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by WojTaKK** [metonator/GameLauncher_NFSW#18]
So i downloaded this game today and i started it like 4 or more times. It was ok. But now it shows me on SBRW Open Beta server that it is online but when i start game it's loading loadin and nothing happens. I allready tried with new acc

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
