### ISSUE TITLE
Game bug

### ISSUE THREAD

**Issue by VladImpaler** [metonator/GameLauncher_NFSW#19]
Hey, I have a problem with infinite loading screen
Can someone help Me?
Nickname: pr0digy
Server: SBRW
Thanks in advance!

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
