### ISSUE TITLE
No Chat/Players/ resetting stats

### ISSUE THREAD

**Issue by Fossilien** [metonator/GameLauncher_NFSW#2]
I can't see opponents. When hitting "R" to search for open events, no events are shown.
I am using the launcher as admin. After an update, all stats get lost because of I have to sign in again.
#stefan.super@gmx.net#  drivername "Fossilium"

thanks for your support

**Comment by Fossilien** [comment]
My launcher is up-to-date

**Comment by LeoCodes21** [comment]
Hi,

I'm the admin of the Open Beta server, which seems to be the server you're playing on.
The racing server is currently unavailable, however I'm working on getting it. The freeroam server is available, but offline, and I am making some updates to it to improve it.

I'll look into the press-R issue. In the future, please report such issues in the Soapbox Race World Discord server, as I do not see all issues opened here.

Thanks!

**Comment by Fossilien** [comment]
I conclude:
multiplayer isn't availabe yet
resetting stats after an update are normal

Is this right?

**Comment by Fossilien** [comment]
Answer by LeoCodes21:
"#1: not really
#2: no"
