### ISSUE TITLE
Infinite Loading Startup

### ISSUE THREAD

**Issue by OmegaZagato** [metonator/GameLauncher_NFSW#20]
It was opening fine this morning then after a few hours, I'm stuck at the infinite loading screen. What can I do to fix this?

**Comment by metonator** [comment]
Write me your ingame name

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
