### ISSUE TITLE
Infinite Loading 

### ISSUE THREAD

**Issue by Kiroshima** [metonator/GameLauncher_NFSW#21]
I wanted to play on the server but the long loading is a little irritating
 Server: SBRW Open Beta
Nickname Kiroshima

**Comment by metonator** [comment]
![discord_2017-09-23_18-47-45 79877959](https://user-images.githubusercontent.com/6225233/30775213-c2ff7c16-a08f-11e7-9763-12a23d4aa806.png)

So, if you had this problem, retry
