### ISSUE TITLE
Where can I download the server files?

### ISSUE THREAD

**Issue by hashnimmo** [metonator/GameLauncher_NFSW#4]
Is there any information about the final version of server files? The current version which Nilzao released in the GitHub page is so hard to host and requires expert knowledge. It doesn't have freeroam synced like the Russian servers, means that the files are available but it wasn't released to the mainstream.

**Comment by metonator** [comment]
Hey, sadly you have to compile it yourself, server source is hosted at https://github.com/SoapboxRaceWorld/soapbox-race-core

**Comment by hashnimmo** [comment]
Does this include freeroam sync like in Russian servers? Also, will this ever be easy to host like other games where I can run a single executable or something to host?

By the way, you have done a great job with the new launcher, the latest unreleased one. I saw it in Discord, looks it's something that everyone can use. Hope this type of advancements will come to the server application too.

**Comment by metonator** [comment]
freeroad is removed from code, it has to be wrote by itself, devs wants to keep that private atm (since its beta, and still being analyzed)

**Comment by hashnimmo** [comment]
OK. Thanks for inside information.
