### ISSUE TITLE
multiplayer Join  Netterror_Handshake_Timout Nettwork Error

### ISSUE THREAD

**Issue by BoostRacerKing** [metonator/GameLauncher_NFSW#6]
If I am on multiplayer and the lobby are a few players inside then start the game and then it happens? Netterror_Handshake_Timout Nettwork Error
and the game does not connect with the others with players ??? this is a bug ??? 

no matter what launcher I tried it has happened !

because my English is not good enough I hope you can understand

**Comment by metonator** [comment]
Known issue, leo is trying to make it work
