### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by BlackZero89** [metonator/GameLauncher_NFSW#7]
The launcher starts to download the game and when it reaches 201 Mb of download it stops and I get the message Download Failed

**Comment by metonator** [comment]
I will try to push tommorow a debug version, so i could take better look where it actually fails. My guess could be temporary internet connection problem.

**Comment by BlackZero89** [comment]
Ok, thanks a lot

**Comment by metonator** [comment]
As promised, update with extra debugs: https://github.com/metonator/GameLauncher_NFSW/releases/download/AppveyorBuild-1.0.0.147/GameLauncher-portable-prerelease.zip

**Comment by BlackZero89** [comment]
Thank you, I'l try it right away

**Comment by metonator** [comment]
Hm, do you have discord or any other communication? We gonna investigate it privately, since its already an issue from your side.

**Comment by BlackZero89** [comment]
Yes I'm on the discord of soapbox my username is BlackZero#9343

**Comment by metonator** [comment]
Closing, ESET was the issue
