### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by SouIwhite** [metonator/GameLauncher_NFSW#9]
I guess its nothing new to you.. 
Also got the "Infinite Loadingscreen" - Username Soulwhite.

Thanks for the help already.

**Comment by metonator** [comment]
Submitted to server admins, they will check what happens.

**Comment by SouIwhite** [comment]
Btw it just happens on SBRW

**Comment by SouIwhite** [comment]
Fixed by deleting the "Settings" Folder in Appdata/Roaming/Need for Speed World.
